---
- hosts: all
  become: true
  vars:
    ansible_user: neto
  tasks:

  - name: Установка nginx
    apt:
      name: nginx
      state: latest

  - name: Включение nginx
    systemd:
      name: nginx
      enabled: true
      state: started

  - name: Изменение стартовой страницы nginx
    ansible.builtin.copy:
      content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to {{ ansible_hostname }} : {{ ansible_ssh_host }}!</title>
          </head>
          <body>
              <h1>Hello from Ansible!</h1>
              <p>This is the new Nginx default page.</p>
          </body>
          </html>
      dest: /var/www/html/index.nginx-debian.html

  - name: Перезагрузка nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
